language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - nightly

sudo: false

before_install:
    - composer self-update
    - cd tests

install:
    - travis_retry composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text

notifications:
  email: false
